In [1]:
import numpy as np
import pandas as pd
import os

In [16]:
from Decomposed_matrices import Decomposed_matrices
from Genomic_bins import Genomic_bins
from great import read_great_res_wrapper

In [3]:
data_dir = '/afs/cs.stanford.edu/u/ytanigaw/repos/lkalesinskas/bigtranscription/private_data'


In [4]:
genomic_bins = Genomic_bins(
    os.path.join(data_dir, 'loci_def.bed')
)

In [5]:
decomposed_mats = Decomposed_matrices(
    os.path.join(data_dir, 'diagonalScore.csv.gz'),
    os.path.join(data_dir, 'uScore.csv.gz'),
    os.path.join(data_dir, 'vScore.csv.gz')
)


### Example: Asthma SNP 17:38023745

Identification of the key component and show the GREAT results for the top component.
We have GREAT results for the following ontologies:

- `GOBiologicalProcess`: Gene ontology biological process.
- `GOCellularComponent`: Gene ontology cellular component.
- `GOMolecularFunction`: Gene ontology molecular function.
- `MGIPhenotype`: Mouse genome informatics (MGI) phenotype ontology. Compared to human, mouse data has relatively comprehensive catalog of gene-phenotype mapping.
- `MGIPhenoSingleKO`: This is a subset of MGI phenotype. The gene-phenotype annotations via gene knock out (KO) experiments are included in this subset.
- `HumanPhenotypeOntology`: Human phenotype ontology.

As an illustration, we just report the results for `HumanPhenotypeOntology` and `GOBiologicalProcess`.

In [10]:
decomposed_mats.find_pcs_given_locus(
    genomic_bins.find_locus_given_snp(17, 38023745)
)

(array([ 7, 39,  5, 41,  1]),
 array([0.07565113, 0.06052896, 0.05604721, 0.04363581, 0.03172747]))

In [23]:
read_great_res_wrapper(data_dir, 7, 'HumanPhenotypeOntology', topk=10)

# ID                                          Desc     BFold  \
1   HP:0010537                          Wide cranial sutures  2.153747   
2   HP:0007648                             Punctate cataract  2.641658   
3   HP:0004492         Widely patent fontanelles and sutures  2.173684   
5   HP:0000894                               Short clavicles  2.020724   
7   HP:0100720               Hypoplasia of the ear cartilage  2.317628   
8   HP:0000064                      Hypoplastic labia minora  2.302681   
13  HP:0000851                     Congenital hypothyroidism  2.302182   
15  HP:0001194  Abnormalities of placenta and umbilical cord  2.080636   
16  HP:0003724                Shoulder girdle muscle atrophy  2.945603   
17  HP:0012056                            Cutaneous melanoma  2.586142   

       BPval      BFDR  
1   0.000546  0.813997  
2   0.000557  0.554162  
3   0.000622  0.463948  
5   0.001024  0.509332  
7   0.001549  0.577449  
8   0.001655  0.548584  
13  0.002230  0.475177  
15  0.003565  0.664566  
16  0.004261  0.747714  
17  0.004444  0.736442

In [24]:
read_great_res_wrapper(data_dir, 7, 'GOBiologicalProcess', topk=10)

# ID                                               Desc     BFold  \
2   GO:0032211  negative regulation of telomere maintenance vi...  3.811605   
5   GO:1900746  regulation of vascular endothelial growth fact...  3.840211   
6   GO:0007004                telomere maintenance via telomerase  3.018872   
7   GO:0051974         negative regulation of telomerase activity  3.131060   
8   GO:0032210  regulation of telomere maintenance via telomerase  2.840701   
9   GO:0045663    positive regulation of myoblast differentiation  2.001179   
11  GO:0032205        negative regulation of telomere maintenance  2.700491   
12  GO:0016233                                   telomere capping  3.819518   
13  GO:0006278                      RNA-dependent DNA replication  2.460045   
14  GO:0032202                                  telomere assembly  3.711348   

       BPval      BFDR  
2   0.000031  0.062514  
5   0.000054  0.054841  
6   0.000083  0.071666  
7   0.000087  0.066323  
8   0.000168  0.113235  
9   0.000267  0.162191  
11  0.000299  0.150884  
12  0.000395  0.184073  
13  0.000426  0.184463  
14  0.000491  0.198721

#### Example multiple SNPs mode for Vitamin D example
- We take four SNPs () and identify the key components and investigate GREAT results

In [27]:
decomposed_mats.find_pcs_given_loci_list(
    genomic_bins.find_loci_given_snps(
        [2, 5, 13, 10],
        [33701000, 1315000, 42952000, 6390000] # this is not the exact coordinate
    ), 
    weights=[1, 1, 1, 1]
)


(array([5, 0, 2, 8, 7]),
 array([0.13214054, 0.05960559, 0.04656923, 0.03709355, 0.036163  ]))

In [28]:
read_great_res_wrapper(data_dir, 5, 'HumanPhenotypeOntology', topk=10)

# ID                                 Desc     BFold         BPval  \
0   HP:0002697                    Parietal foramina  2.372433  4.367679e-08   
1   HP:0004425                        Flat forehead  2.735910  1.568965e-06   
3   HP:0004442            Sagittal craniosynostosis  2.733096  2.359962e-06   
4   HP:0002365          Hypoplasia of the brainstem  2.031767  2.396735e-06   
5   HP:0010054  Abnormality of the first metatarsal  2.574793  2.506458e-06   
7   HP:0006191                   Deep palmar crease  2.977180  4.189624e-06   
8   HP:0000557                          Buphthalmos  2.287392  4.706791e-06   
12  HP:0009836       Broad distal phalanx of finger  2.601329  1.739019e-05   
18  HP:0003741        Congenital muscular dystrophy  2.094681  3.098136e-05   
21  HP:0003535          3-Methylglutaconic aciduria  2.428799  3.861840e-05   

        BFDR  
0   0.000130  
1   0.002340  
3   0.001760  
4   0.001430  
5   0.001246  
7   0.001562  
8   0.001560  
12  0.003990  
18  0.004864  
21  0.005236